datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://37.228.117.30:5439/fb
  username: postgres
  password: postgres

jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  generate-ddl: false
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
