spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://37.228.117.30:5439/fb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  sms:
    login: foodbooking
    password: foodyaka-100
    url: https://smsc.ru/sys/send.php
  mail:
    host: smtp.mail.ru
    username: info@foodbooking.ru
    password: de!4H3ywsAHX
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true

server:
  port: 8009
